### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by dmnc-net** [pR0Ps/grafana-trackmap-panel#7]
Hi, when trying to install this plugin (`git clone ...`, `npm install`, `npm run build`), I'm getting a lot of warnings and errors. I've tried to update packages, run `npm audit fix` as npm told me, install grunt but I can't build that. This is a debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana-trackmap-panel@1.1.0~prebuild: grafana-trackmap-panel@1.1.0
6 info lifecycle grafana-trackmap-panel@1.1.0~build: grafana-trackmap-panel@1.1.0
7 verbose lifecycle grafana-trackmap-panel@1.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle grafana-trackmap-panel@1.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/lib/grafana/plugins/grafana-trackmap-panel/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle grafana-trackmap-panel@1.1.0~build: CWD: /var/lib/grafana/plugins/grafana-trackmap-panel
10 silly lifecycle grafana-trackmap-panel@1.1.0~build: Args: [ '-c', 'grunt' ]
11 info lifecycle grafana-trackmap-panel@1.1.0~build: Failed to exec build script
12 verbose stack Error: grafana-trackmap-panel@1.1.0 build: `grunt`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid grafana-trackmap-panel@1.1.0
14 verbose cwd /var/lib/grafana/plugins/grafana-trackmap-panel
15 verbose Linux 4.9.0-4-amd64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
17 verbose node v11.0.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error grafana-trackmap-panel@1.1.0 build: `grunt`
23 error spawn ENOENT
24 error Failed at the grafana-trackmap-panel@1.1.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by pR0Ps** [comment]
Thanks for pointing this out. I updated all the deps to their latest versions to resolve the security issues. Before I updated them I didn't see anything like the error you posted though so hopefully updating the deps fixed that too (feel free to reopen if not).

**Comment by rajeshtaneja** [comment]
Is there any place I can  download zip plugin which I can install and play with ?

**Comment by pR0Ps** [comment]
@rajeshtaneja: Starting with version 2.0.0, you can download the compiled plugin from the [releases page](https://github.com/pR0Ps/grafana-trackmap-panel/releases/). You can download v2.0.0 [here](https://github.com/pR0Ps/grafana-trackmap-panel/archive/v2.0.0.zip).
